---
version: 0.2

branches:
  feature/*, improvement/*, bugfix/*, w/*, q/*, hotfix/*, ft/*, bf/*, chore/*, docs/*:
    stage: "pre-merge"

stages:
  pre-merge:
    worker:
      type: docker
      path: eve/workers/unit_and_feature_tests
      volumes:
        - '/home/eve/workspace'
    steps:
      - Git:
          name: fetch source
          repourl: '%(prop:git_reference)s'
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: Npm install
          command: npm install --unsafe-perm
      - ShellCommand:
          name: run static analysis tools on markdown
          command: npm run --silent lint_md
      - ShellCommand:
          name: run static analysis tools on code
          command: npm run --silent lint
      - ShellCommand:
          name: run unit tests
          command: npm test
      - ShellCommand:
          name: run s3 server and run feature tests
          command: bash ./eve/workers/unit_and_feature_tests/run_server_tests.bash
          workdir: '%(prop:builddir)s/build'
  nightly:
    worker:
      type: docker
      path: eve/workers/nightly_build
    steps:
      - Git:
          name: Fetch source
          repourl: '%(prop:git_reference)'
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: Build docker image
          workdir: '%(prop:builddir)s/build'
          command: docker build -t scality/backbeat:%(prop:image_tag) .
      - ShellCommand:
          name: Push docker image
          command: docker push scality/backbeat:%(prop:image_tag)
          haltOnFailure: True
      - ShellCommand:
          name: Run integration test
          command: 'true'
          haltOnFailure: True
